---
- name: Obtain v4 Cloudflare IPs
  uri:
    url: https://www.cloudflare.com/ips-v4
    return_content: yes
  register: cloudflare_ipv4

- include_role:
    name: bviktor.firewalld
  vars:
    zone: 'cloudflare'
    source: "{{ item }}"
  loop: "{{ cloudflare_ipv4.content.split() }}"

- name: Obtain v6 Cloudflare IPs
  uri:
    url: https://www.cloudflare.com/ips-v6
    return_content: yes
  register: cloudflare_ipv6

- include_role:
    name: bviktor.firewalld
  vars:
    zone: 'cloudflare'
    source: "{{ item }}"
  loop: "{{ cloudflare_ipv6.content.split() }}"

# we could define service in the above include, but it's faster to enable it only once instead of all elements in the loop
- include_role:
    name: bviktor.firewalld
  vars:
    zone: 'cloudflare'
    service: 'https'
