---
- name: Check firewalld state
  command:
    cmd: systemctl status firewalld
  changed_when: false
  failed_when: false
  register: fwd_state

- debug:
    msg: "{{ fwd_state }}"

- name: Check firewalld state 2
  command:
    cmd: cat /var/log/firewalld
  changed_when: false
  failed_when: false
  register: fwd_state2

- debug:
    msg: "{{ fwd_state2 }}"

- name: Obtain v4 Cloudflare IPs
  uri:
    url: https://www.cloudflare.com/ips-v4
    return_content: true
  register: cloudflare_ipv4

- include_role:
    name: bviktor.firewalld
  vars:
    zone: 'cloudflare'
    source: "{{ item }}"
  loop: "{{ cloudflare_ipv4.content.split() }}"

- name: Obtain v6 Cloudflare IPs
  uri:
    url: https://www.cloudflare.com/ips-v6
    return_content: true
  register: cloudflare_ipv6

- include_role:
    name: bviktor.firewalld
  vars:
    zone: 'cloudflare'
    source: "{{ item }}"
  loop: "{{ cloudflare_ipv6.content.split() }}"

# we could define service in the above include, but it's faster to enable it only once instead of all elements in the loop
- include_role:
    name: bviktor.firewalld
  vars:
    zone: 'cloudflare'
    service: 'https'
