---
- include_role:
    name: noobient.update

- include_role:
    name: noobient.thirdparty
  vars:
    name: Cloudflare Tunnel
    gpg_url: "https://pkg.cloudflare.com/cloudflare-{% if ansible_pkg_mgr == 'dnf' %}ascii-pubkey{% else %}main{% endif %}.gpg"
    repo_file: cloudflared
    package: cloudflared

- name: Deploy Cloudflare daemon
  template:
    src: cloudflared.service.j2
    dest: /etc/systemd/system/cloudflared.service

- name: Enable and start Cloudflare daemon
  systemd:
    name: cloudflared.service
    enabled: true
    state: started
    daemon_reload: true
