---
- include_role:
    name: noobient.thirdparty
  vars:
    name: Cloudflare Tunnel
    gpg_url: "https://pkg.cloudflare.com/cloudflare-{% if ansible_os_family == 'RedHat' %}ascii-pubkey{% else %}main{% endif %}.gpg"
    repo_file: cloudflared
    package: cloudflared

- name: Deploy Cloudflare daemon
  template:
    src: cloudflared.service.j2
    dest: /etc/systemd/system/cloudflared.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Cloudflare daemon

- name: Enable and start Cloudflare daemon
  systemd:
    name: cloudflared.service
    enabled: true
    state: started
    daemon_reload: true
